---
title: ""
author: "Qiu Wen"
date: ""
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    toc: true
    toc_flaot: true
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include=FALSE}
library(knitr)
## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
                 cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               message=FALSE,
               warning=FALSE,
               collapse = TRUE, dev='cairo_pdf', out.width="1000px", out.height="1000px")
opts_knit$set(width=75)
```

```{r}
library(tidyverse)
library(ggpubr)
source("/data/scripts/utility.R")

extract_dist = function(dist, x1, x2, name, day){
  x1 = intersect(rownames(dist), x1)
  x2 = intersect(rownames(dist), x2)
  dist[x1, x2] %>% 
    pivot_longer(everything(), names_to = "group", values_to = "distance") %>% 
    mutate(Day = day, 
           Group = name) %>% 
    select(-group)
}


```




```{r}
distance = "bray_curtis"
meta = "../../Metadata_infant_stool_microbiome.txt"
yname ="Bray-Curtis dissimilarity"
y.npc = 0.75
```

```{r}
distance_compare = function(distance, meta, yname, y.npc){
  

meta = read_tsv(meta)


D3_dist = read.table(paste0("D3_bdiv/", distance, "_dm.txt"), row.names = 1) 
D7_dist = read.table(paste0("D7_bdiv/", distance, "_dm.txt"), row.names = 1) 
D30_dist = read.table(paste0("D30_bdiv/", distance, "_dm.txt"), row.names = 1) 
D42_dist = read.table(paste0("D42_bdiv/", distance, "_dm.txt"), row.names = 1) 




D3_Con_sp = meta %>% filter(Group == "Con" & Day == "D3") %>% pull(`#SampleID`)
D3_VMT_sp = meta %>% filter(Group == "VMT" & Day == "D3") %>% pull(`#SampleID`)
D3_VD_sp = meta %>% filter(Group == "VD" & Day == "D3") %>% pull(`#SampleID`)

D7_Con_sp = meta %>% filter(Group == "Con" & Day == "D7") %>% pull(`#SampleID`)
D7_VMT_sp = meta %>% filter(Group == "VMT" & Day == "D7") %>% pull(`#SampleID`)
D7_VD_sp = meta %>% filter(Group == "VD" & Day == "D7") %>% pull(`#SampleID`)

D30_Con_sp = meta %>% filter(Group == "Con" & Day == "D30") %>% pull(`#SampleID`)
D30_VMT_sp = meta %>% filter(Group == "VMT" & Day == "D30") %>% pull(`#SampleID`)
D30_VD_sp = meta %>% filter(Group == "VD" & Day == "D30") %>% pull(`#SampleID`)

D42_Con_sp = meta %>% filter(Group == "Con" & Day == "D42") %>% pull(`#SampleID`)
D42_VMT_sp = meta %>% filter(Group == "VMT" & Day == "D42") %>% pull(`#SampleID`)
D42_VD_sp = meta %>% filter(Group == "VD" & Day == "D42") %>% pull(`#SampleID`)




D3_VD_VMT = extract_dist(D3_dist, D3_VD_sp, D3_VMT_sp, "VD_vs_VMT", "D3")
D3_VD_Con = extract_dist(D3_dist, D3_VD_sp, D3_Con_sp, "VD_vs_Con", "D3")

D7_VD_VMT = extract_dist(D7_dist, D7_VD_sp, D7_VMT_sp, "VD_vs_VMT", "D7")
D7_VD_Con = extract_dist(D7_dist, D7_VD_sp, D7_Con_sp, "VD_vs_Con", "D7")

D30_VD_VMT = extract_dist(D30_dist, D30_VD_sp, D30_VMT_sp, "VD_vs_VMT", "D30")
D30_VD_Con = extract_dist(D30_dist, D30_VD_sp, D30_Con_sp, "VD_vs_Con", "D30")

D42_VD_VMT = extract_dist(D42_dist, D42_VD_sp, D42_VMT_sp, "VD_vs_VMT", "D42")
D42_VD_Con = extract_dist(D42_dist, D42_VD_sp, D42_Con_sp, "VD_vs_Con", "D42")


VD_with_Con_VMT_dist = bind_rows(D3_VD_VMT, D3_VD_Con, 
                               D7_VD_VMT, D7_VD_Con, D30_VD_VMT, D30_VD_Con, D42_VD_VMT, D42_VD_Con) %>% 
  mutate(Day = fct_relevel(Day, c("D3", "D7", "D30", "D42")), 
         Group = case_when(Group == "VD_vs_Con" ~ "VD_vs_Con", 
                           Group == "VD_vs_VMT" ~ "VD_vs_VMT"))


p3 = ggplot(VD_with_Con_VMT_dist, aes(Day, distance, fill = Group)) + 
  geom_boxplot(outlier.alpha = 0.5, outlier.size = 0.7, outlier.shape = NA) + 
  #scale_fill_manual(values = c('#1f77b4', '#ff7f0e', '#2ca02c')) + 
  scale_fill_manual(values = c('#7bc2ce', '#8562cc', '#2ca02c')) + 
  theme_minimal() + 
  labs(y = yname) +
  stat_compare_means(aes(group = Group), label = "p.signif", method = "wilcox.test", label.y.npc = 0.5) + 
  coord_cartesian(ylim = c(0.4, 1)) + 
  theme(legend.position = "bottom")




p4 = ggline(VD_with_Con_VMT_dist, x = "Day", y = "distance", add = "mean_se", color = "Group", 
            #palette = c('#1f77b4', '#ff7f0e', '#2ca02c'), 
            palette = c('#7bc2ce', '#8562cc', '#2ca02c'), 
            point.size =1, size = 0.8, shape = 16, 
       error.plot = "errorbar", ggtheme = theme_minimal(), ylab = yname) + 
  stat_compare_means(aes(group = Group), label = "p.signif", method = "wilcox.test", label.y.npc = y.npc)+ 
  theme(legend.position = "bottom", 
        panel.border = element_rect(fill = "transparent", color = "black")) +
  ylab("Bray-Curtis dissimilarity to VD")

return(list(boxplot = p3, lineplot = p4, data = VD_with_Con_VMT_dist))
}

```



```{r, fig.width=3.5, fig.height=3.5}
BC = distance_compare("bray_curtis", "../../../Metadata_infant_stool_microbiome.txt", "Bray-Curtis dissimilarity", 0.95)
write_rds(BC$data, "VD_with_VMTandCon_distance_weighted_unifrac.RDS")

BC$lineplot
ggsave("fig1e-VD组到CS组的距离比较折线图_weighted_unifrac.pdf", width = 3.5, height = 3.5)
BC$boxplot
ggsave("VD组到CS组的距离比较箱线图_weigted_unifrac.pdf", width = 3.5, height = 3.5)


```
```{r}
all_distances = list.files("D1_bdiv/", pattern = ".*dm.txt") %>% 
  str_extract(".*(?=_)")

all_lineplot = map(all_distances, ~distance_compare(.x, "../../Metadata_infant_stool_microbiome.txt", .x, 0.5))

#pdf("all_distance_compare_lineplot.pdf", width = 3.5, height = 3.5)
walk(all_lineplot, ~print(.x$lineplot))
#dev.off()
```
组内距离
```{r}

D3_dist = read.table("D3_bdiv/weighted_unifrac_dm.txt", row.names = 1) 
D7_dist = read.table("D7_bdiv/weighted_unifrac_dm.txt", row.names = 1) 
D30_dist = read.table("D30_bdiv/weighted_unifrac_dm.txt", row.names = 1) 
D42_dist = read.table("D42_bdiv/weighted_unifrac_dm.txt", row.names = 1) 



D3_meta = read_tsv("../Metadata_infant_stool_microbiome__Day_D3__.txt")
D7_meta = read_tsv("../Metadata_infant_stool_microbiome__Day_D7__.txt")
D30_meta = read_tsv("../Metadata_infant_stool_microbiome__Day_D30__.txt")
D42_meta = read_tsv("../Metadata_infant_stool_microbiome__Day_D42__.txt")
```

```{r}

D3_Con_sp = D3_meta %>% filter(Group == "Con") %>% pull(`#SampleID`)
D3_VMT_sp = D3_meta %>% filter(Group == "VMT") %>% pull(`#SampleID`)
D3_VD_sp = D3_meta %>% filter(Group == "VD") %>% pull(`#SampleID`)

D7_Con_sp = D7_meta %>% filter(Group == "Con") %>% pull(`#SampleID`)
D7_VMT_sp = D7_meta %>% filter(Group == "VMT") %>% pull(`#SampleID`)
D7_VD_sp = D7_meta %>% filter(Group == "VD") %>% pull(`#SampleID`)

D30_Con_sp = D30_meta %>% filter(Group == "Con") %>% pull(`#SampleID`)
D30_VMT_sp = D30_meta %>% filter(Group == "VMT") %>% pull(`#SampleID`)
D30_VD_sp = D30_meta %>% filter(Group == "VD") %>% pull(`#SampleID`)

D42_Con_sp = D42_meta %>% filter(Group == "Con") %>% pull(`#SampleID`)
D42_VMT_sp = D42_meta %>% filter(Group == "VMT") %>% pull(`#SampleID`)
D42_VD_sp = D42_meta %>% filter(Group == "VD") %>% pull(`#SampleID`)

# 根据样本返回组内距离
func1 = function(distance_matrix, Sample, Group){
  Dn_dist = distance_matrix[Sample, Sample]
  idx = upper.tri(Dn_dist, diag = T)
  Dn_dist[idx] = NA
  Dn_dist = Dn_dist %>% rownames_to_column(var = "Sample") %>% 
    pivot_longer(-Sample, names_to = "Sample2", values_to = "distance") %>% 
    filter(!is.na(distance)) %>% 
    mutate(Group = Group) %>% 
    select(-Sample, -Sample2)
  return(Dn_dist)
}



D3_distance_within_Group = bind_rows(func1(D3_dist, D3_Con_sp, "Con"), func1(D3_dist, D3_VMT_sp, "VMT"), func1(D3_dist, D3_VD_sp, "VD")) %>% mutate(Day = "D3")
D7_distance_within_Group = bind_rows(func1(D7_dist, D7_Con_sp, "Con"), func1(D7_dist, D7_VMT_sp, "VMT"), func1(D7_dist, D7_VD_sp, "VD")) %>% mutate(Day = "D7")
D30_distance_within_Group = bind_rows(func1(D30_dist, D30_Con_sp, "Con"), func1(D30_dist, D30_VMT_sp, "VMT"), func1(D30_dist, D30_VD_sp, "VD")) %>% mutate(Day = "D30")
D42_distance_within_Group = bind_rows(func1(D42_dist, D42_Con_sp, "Con"), func1(D42_dist, D42_VMT_sp, "VMT"), func1(D42_dist, D42_VD_sp, "VD")) %>% mutate(Day = "D42")

distance_within_Group = bind_rows(D3_distance_within_Group, D7_distance_within_Group, D30_distance_within_Group, D42_distance_within_Group) %>% 
  mutate(Day = fct_relevel(Day, c("D3", "D7", "D30", "D42")))

saveRDS(distance_within_Group, "各组各时间点组内距离_weighted_unifrac.RDS")
```


```{r}
distance_within_Group = distance_within_Group %>% filter(Group != "VD")
p3 = ggplot(distance_within_Group, aes(Day, distance, fill = Group)) + 
  geom_boxplot(outlier.alpha = 0.5, outlier.size = 0.7, outlier.shape = NA) + 
  #scale_fill_manual(values = c('#1f77b4', '#ff7f0e', '#2ca02c')) + 
  scale_fill_manual(values = c('#7bc2ce', '#8562cc', '#2ca02c')) + 
  theme_minimal() + 
  labs(y = yname) +
  stat_compare_means(aes(group = Group), label = "p.signif", method = "wilcox.test", label.y.npc = 1) + 
  #coord_cartesian(ylim = c(0.4, 1)) + 
  theme(legend.position = "bottom")
p3



p4 = ggline(distance_within_Group, x = "Day", y = "distance", add = "mean_se", color = "Group", 
            #palette = c('#1f77b4', '#ff7f0e', '#2ca02c'), 
            palette = c('#7bc2ce', '#8562cc', '#2ca02c'), 
            point.size =1, size = 0.8, shape = 16, 
       error.plot = "errorbar", ggtheme = theme_minimal(), ylab = yname) + 
  stat_compare_means(aes(group = Group), label = "p.signif", method = "wilcox.test", label.y.npc = 0.43)+ 
  theme(legend.position = "bottom")
p4
library(patchwork)
p3+p4
ggsave("组内距离比较weighted_unifrac.pdf", width = 8, height = 3.5)
```

